feat: eastern mediterranean malaria repo landing page
EyeSeeTea/landing-page-app pull request #43
Opened 2022-07-27 13:39 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/345yjdn

### :art: Screenshots
<img width="1440" alt="Screenshot 2022-07-27 at 14 37 50" src="https://user-images.githubusercontent.com/37223065/181260894-75f3758d-5a6d-4ad4-ab61-657064076545.png">
<img width="1440" alt="Screenshot 2022-07-27 at 14 38 16" src="https://user-images.githubusercontent.com/37223065/181260999-28dd64f6-8ae4-4035-9893-b981ee155fa6.png">

2022-08-08 09:42 UTC, tokland approved these changes
Code-wise, the PR looks good, I just added some a comment about the styles, but's it's very minor.

2022-08-08 09:42 UTC, tokland commented on src/domain/models/east_mediterranian_mal/Malaria.jsx
> +            <p style={{ textAlign: "left" }}>{i18n.t("This repository will be useful for the following:")}</p>
Move to styles object or styled-components or useStyles, whatever the rest of the app is using.

2022-08-18 07:09 UTC, ifoche requested changes
From a functional perspective, at least for me I'm not being redirected to the right place when I click on any link. I'm basically taken to the landing page again... @deeonwuli is it working for you?

2022-08-18 08:04 UTC, deeonwuli commented
> From a functional perspective, at least for me I'm not being redirected to the right place when I click on any link. I'm basically taken to the landing page again... @deeonwuli is it working for you?

it wasn't working but i just pushed a fix and only the Data Quality Dashboard isn't working now seeing as we still don't have a link for that @ifoche

2022-08-23 09:21 UTC, ifoche requested changes
Thank you @deeonwuli . From a functional perspective, now the links take to the appropriate place (but from the data quality dashboard, that the client yet has to provide it). 

The client provided the group that this landing page should be exposed to. It is a group that doesn't exist in the instance you're testing, but could you please make the change already?

User Group Name: MAL_EMRO Repository
User Group ID: FpQ7a5OylZH

![screenshots_1661246345_1119_23082022_599x346](https://user-images.githubusercontent.com/10931645/186121969-1dba403c-3e26-43b5-add2-ebdb3b5020a1.png)

Thank you!

2022-08-23 12:44 UTC, ifoche requested changes
Just realized that while the EMRO WHO logo has been updated when you're inside the landing pag
![screenshots_1661258658_1444_23082022_1766x340](https://user-images.githubusercontent.com/10931645/186161151-7e6d3938-726f-42b1-9771-0c820a7f5abc.png)
e...


however, from outside, when you're looking at all the available landing pages, the old logo remains there...
![screenshots_1661258495_1441_23082022_1317x782](https://user-images.githubusercontent.com/10931645/186161184-3b1074cb-523e-48e2-bc34-600b9533735c.png)

Could you please change the icon there too?

2022-08-23 12:55 UTC, deeonwuli commented
> Just realized that while the EMRO WHO logo has been updated when you're inside the landing page... ![screenshots_1661258658_1444_23082022_1766x340](https://user-images.githubusercontent.com/10931645/186161151-7e6d3938-726f-42b1-9771-0c820a7f5abc.png)
> 
> however, from outside, when you're looking at all the available landing pages, the old logo remains there... ![screenshots_1661258495_1441_23082022_1317x782](https://user-images.githubusercontent.com/10931645/186161184-3b1074cb-523e-48e2-bc34-600b9533735c.png)
> 
> Could you please change the icon there too?

@ifoche when i change the icon in the available landing pages to the new icon, it doesn't show because it's the same white colour as the background.

2022-08-23 12:57 UTC, ifoche commented
I see, let me ask Ray to create a blue-foreground version of that logo and provide it to you in the clickup ticket

2022-08-24 13:29 UTC, ifoche requested changes
thanks for the logo change @deeonwuli . I think we're almost there. Now if you could take a look to the comments from Ray in the ticket and try to implement some of the changes... it doesn't need to be all of them, but at least some of them so the aspect of the landing is more appealing. 

In particular I think that what's about the content is something that the client has established so we cannot change it before talking to him (I have a meeting with him on Friday). But for instance, it looks like the welcome text title color change plus the redistribution of the bullet points could be a huge improvement, plus some padding between the 5 options below, only those things would already do a big change. 

In addition, if you could also add the following description to the WHO Data Quality App:
WHO Data Quality Tool for DHIS2, based on the WHO Data Quality Framework.

I think at least there is something there, even if it is not same length of the other entries

2022-08-24 17:31 UTC, merged